levels = [
('ep1sc1.scene', 'Episode 1: Prologue', None, None),
('ep1st1.stage', 'Learning To Burgle', 'SomethingDoing.mp3', 'ep1st1.png'),
('ep1st2.stage', 'Switching Canisters', 'SomethingDoing.mp3', 'ep1st2.png'),
('ep1st3.stage', 'Advanced Thievery', 'SomethingDoing.mp3', 'ep1st3.png'),
('ep1sc2.scene', 'Episode 1: Intermezzo', None, None),
('ep1st4.stage', 'Treasure Hunt', 'TheEasyWinners.mp3', 'ep1st4.png'),
('ep1st5.stage', 'Octopus\' Garden', 'TheEasyWinners.mp3', 'ep1st5.png'),
('ep1st6.stage', 'Water Relief', 'TheEasyWinners.mp3', 'ep1st6.png'),
('ep1sc3.scene', 'Episode 1: Epilogue', None, None),

('ep2sc1.scene', 'Episode 2: Prologue', None, None),
('ep2st1.stage', 'Hive and Seek', 'WeepingWillow.mp3', 'ep2st1.png'),
('ep2st2.stage', 'Oh Beehave!', 'WeepingWillow.mp3', 'ep2st2.png'),
('ep2st3.stage', 'Honey, I Stole The Crown', 'WeepingWillow.mp3', 'ep2st3.png'),
('ep2sc2.scene', 'Episode 2: Intermezzo', None, None),
('ep2st4.stage', 'Burglars Are From Mars, Women Are From Venus', 'MapleLeafRag.mp3', 'ep2st4.png'),
('ep2st5.stage', 'Great Eggspectations', 'MapleLeafRag.mp3', 'ep2st5.png'),
('ep2st6.stage', 'Flower Power', 'MapleLeafRag.mp3', 'ep2st6.png'),
('ep2sc3.scene', 'Episode 2: Epilogue', None, None),

('ep3sc1.scene', 'Episode 3: Prologue', None, None),
('ep3st1.stage', 'Just Deserts', 'TheCrushCollisionMarch.mp3', 'ep3st1.png'),
('ep3st2.stage', 'A-Maze-Ing', 'TheCrushCollisionMarch.mp3', 'ep3st2.png'),
('ep3st3.stage', 'Some Mummies Do Have\'em', 'TheCrushCollisionMarch.mp3', 'ep3st3.png'),
('ep3sc2.scene', 'Episode 3: Intermezzo', None, None),
('ep3st4.stage', 'Getting Into The Festive Spirit', 'EliteSyncopations.mp3', 'ep3st4.png'),
('ep3st5.stage', 'There\'s No Business Like Snow Business', 'EliteSyncopations.mp3', 'ep3st5.png'),
('ep3st6.stage', 'Escape Claus', 'EliteSyncopations.mp3', 'ep3st6.png'),
('ep3sc3.scene', 'Episode 3: Epilogue', None, None),
]
